$HOME/.config/hypr/themes/theme.conf|> $HOME/.config/hypr/themes/colors.conf

$GTK_THEME= VALYRIAN-Blue-Steel
$ICON_THEME= Breeze-Noir-White-Blue
$COLOR_SCHEME= prefer-dark
$CURSOR_THEME= Bibata-Modern-Classic
$CURSOR_SIZE= 20


#? For anyone using the old implementaiton of hyprdots
#? You can use the following commands to set the following
#? This is not needed for the new implementation as this makes it slower

exec = gsettings set org.gnome.desktop.interface icon-theme 'Breeze-Noir-White-Blue'
exec = gsettings set org.gnome.desktop.interface gtk-theme 'VALYRIAN-Blue-Steel'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec = gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Classic'
exec = hyprctl setcursor Bibata-Modern-Classic 20
exec = gsettings set org.gnome.desktop.interface cursor-size 20


general { 
    gaps_in = 1
    gaps_out = 2
    col.active_border = rgba(00c1e4cc) rgb(B0E0E6) rgb(B0E0E6) rgba(00c1e4cc) 90deg
    col.inactive_border = rgb(98FB98) rgb(2E8B57) rgb(2E8B57) rgb(98FB98) 90deg
    border_size = 1
    resize_on_border = true
    allow_tearing = false
    layout = dwindle
}

decoration {
  rounding = 7
  active_opacity = 1
  inactive_opacity = 0.999
  blur {
    enabled = true
    size = 4
    passes = 2
    noise= 0.01
    vibrancy = 1
  }
}
layerrule=unset,waybar
