$HOME/.config/hypr/themes/theme.conf|> $HOME/.config/hypr/themes/colors.conf
#  // Custom Poimandres Theme

# Note: You may want to look into a matching GTK/Icon theme like 'TokyoNight' or a custom oomox-generated one to match Poimandres!
$GTK_THEME = Poimandres
$ICON_THEME = Tela-circle-blue
$COLOR_SCHEME = prefer-dark

# Optional: The variables above will be set automatically when the theme is loaded
# This exec commands will soon be deprecated

exec = gsettings set org.gnome.desktop.interface icon-theme $ICON_THEME
exec = gsettings set org.gnome.desktop.interface gtk-theme $GTK_THEME
exec = gsettings set org.gnome.desktop.interface color-scheme $COLOR_SCHEME

general {
    gaps_in = 3
    gaps_out = 8
    border_size = 2
    col.active_border = rgba(89ddffff) rgba(adc7ffff) 45deg
    col.inactive_border = rgba(2b3040cc) rgba(48506acc) 45deg
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(89ddffff) rgba(adc7ffff) 45deg
    col.border_inactive = rgba(2b3040cc) rgba(48506acc) 45deg
    col.border_locked_active = rgba(89ddffff) rgba(adc7ffff) 45deg
    col.border_locked_inactive = rgba(2b3040cc) rgba(48506acc) 45deg
}

decoration {
    rounding = 10
    shadow:enabled = false

    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
        xray = false
    }
}

layerrule = blur,waybar
