#!/bin/bash

# TODO: look into removing borders dir entirely for Linux

{{ if eq .chezmoi.os "darwin" }}
## See yabai/yabairc for bootstrapped command
## TODO: use this config file from there

#options=(
#	#style=round
#	style=square
#	width=3.0
#	hidpi=off
#	active_color=0xff660bb5
#	inactive_color=0xff414550
#)
#
#borders "${options[@]}"
{{ end }}
