#!/bin/bash

if [ -z "$IS_DARK" ]; then
    IS_DARK=$(osascript -e 'tell application "System Events" to tell appearance preferences to return dark mode' 2>/dev/null)
fi

if [ "$IS_DARK" = "true" ]; then
    ACTIVE_COLOR="0xff1C1E28"
    INACTIVE_COLOR="0xff1C1E28"
else
    ACTIVE_COLOR="0xffffffff"
    INACTIVE_COLOR="0xffffffff"
fi

options=(
    style=square
    order=above
    width=3.0
    hidpi=off
    active_color="$ACTIVE_COLOR"
    inactive_color="$INACTIVE_COLOR"
)

borders "${options[@]}"
