$HOME/.config/hypr/themes/theme.conf|> $HOME/.config/hypr/themes/colors.conf
#  // P̳r̳a̳s̳a̳n̳t̳h̳ R̳a̳n̳g̳a̳n̳

$GTK_THEME=Grukai
$ICON_THEME=buuf-icons-for-plasma
$COLOR_SCHEME=prefer-dark
$CURSOR_THEME=Simp1e
$CURSOR_SIZE=18
$FONT = Inter


# Optional: The varibles above will be set automatically when the theme is loaded
# This exec commands will soon be deprecated


general {
    gaps_in = 3
    gaps_out = 5
    border_size = 2
    col.active_border = rgba(B3BBA3ff) rgba(1A1A1Aff) 45deg
    col.inactive_border = rgba(232425ff) rgba(444742ff) 45deg
    layout = dwindle
    resize_on_border = true
}

group {
    col.border_active = rgba(B3BBA3ff) rgba(1A1A1Aff) 45deg
    col.border_inactive = rgba(232425cc) rgba(444742cc) 45deg
    col.border_locked_active = rgba(FFFFFFff) rgba(0D0D0Dff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}

decoration {
    rounding = 8
    shadow:enabled = true

    active_opacity = 0.95
    inactive_opacity = 0.8

    dim_inactive = true
    dim_strength = 0.15

    blur {
        enabled = yes
        size = 2
        passes = 7
        new_optimizations = on
        ignore_opacity = on
        xray = false
        brightness = 0.9
    }

    shadow {
        enabled = true
        ignore_window = false
        offset = 4 4 4 4
        range = 9
        render_power = 1
        scale = 1.0
        color = 0xaa130d06
        color_inactive = 0x66130d06
    }
}

layerrule = blur on, match:namespace waybar
